/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package defisheye;

/**
 *
 * @author Dzmitry
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTypeGroup = new javax.swing.ButtonGroup();
        panelImages = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        panelTool = new javax.swing.JPanel();
        labelTransform = new javax.swing.JLabel();
        labelProcessing = new javax.swing.JLabel();
        labelRotate = new javax.swing.JLabel();
        sliderCorrection = new javax.swing.JSlider();
        checkBoxPreview = new javax.swing.JCheckBox();
        checkBoxAntialiased = new javax.swing.JCheckBox();
        radioButtonDiagonal = new javax.swing.JRadioButton();
        labelTypeImage = new javax.swing.JLabel();
        radioButtonCircular = new javax.swing.JRadioButton();
        labelCorrectionImage = new javax.swing.JLabel();
        sliderRotate = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemClose = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemUndo = new javax.swing.JMenuItem();
        menuItemRedo = new javax.swing.JMenuItem();
        menuItemReset = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1024, 768));

        panelImages.setBackground(new java.awt.Color(0, 0, 51));
        panelImages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/icons-images-500.png"))); // NOI18N
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imageLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelImagesLayout = new javax.swing.GroupLayout(panelImages);
        panelImages.setLayout(panelImagesLayout);
        panelImagesLayout.setHorizontalGroup(
            panelImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        panelImagesLayout.setVerticalGroup(
            panelImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTool.setBackground(new java.awt.Color(0, 204, 204));
        panelTool.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelTransform.setBackground(new java.awt.Color(0, 153, 153));
        labelTransform.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelTransform.setForeground(new java.awt.Color(255, 255, 255));
        labelTransform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransform.setText("Transformation");
        labelTransform.setToolTipText("");
        labelTransform.setOpaque(true);

        labelProcessing.setBackground(new java.awt.Color(0, 153, 153));
        labelProcessing.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelProcessing.setForeground(new java.awt.Color(255, 255, 255));
        labelProcessing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessing.setText("Processing");
        labelProcessing.setToolTipText("");
        labelProcessing.setOpaque(true);

        labelRotate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelRotate.setForeground(new java.awt.Color(255, 255, 255));
        labelRotate.setText("Rotate:");

        sliderCorrection.setBackground(new java.awt.Color(0, 204, 204));
        sliderCorrection.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        sliderCorrection.setForeground(new java.awt.Color(255, 255, 255));
        sliderCorrection.setMajorTickSpacing(1);
        sliderCorrection.setMinorTickSpacing(1);
        sliderCorrection.setPaintTicks(true);
        sliderCorrection.setSnapToTicks(true);
        sliderCorrection.setToolTipText("Rotate");
        sliderCorrection.setValue(0);
        sliderCorrection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderCorrection.setVerifyInputWhenFocusTarget(false);

        checkBoxPreview.setBackground(new java.awt.Color(0, 204, 204));
        checkBoxPreview.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        checkBoxPreview.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPreview.setText("Preview");

        checkBoxAntialiased.setBackground(new java.awt.Color(0, 204, 204));
        checkBoxAntialiased.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        checkBoxAntialiased.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxAntialiased.setText("Antialiased");
        checkBoxAntialiased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAntialiasedActionPerformed(evt);
            }
        });

        radioButtonDiagonal.setBackground(new java.awt.Color(0, 204, 204));
        buttonTypeGroup.add(radioButtonDiagonal);
        radioButtonDiagonal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        radioButtonDiagonal.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonDiagonal.setText("Full-frame fisheye");

        labelTypeImage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelTypeImage.setForeground(new java.awt.Color(255, 255, 255));
        labelTypeImage.setText("Type of the image:");

        radioButtonCircular.setBackground(new java.awt.Color(0, 204, 204));
        buttonTypeGroup.add(radioButtonCircular);
        radioButtonCircular.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        radioButtonCircular.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonCircular.setText("Circular fisheye");

        labelCorrectionImage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelCorrectionImage.setForeground(new java.awt.Color(255, 255, 255));
        labelCorrectionImage.setText("Correction:");

        sliderRotate.setBackground(new java.awt.Color(0, 204, 204));
        sliderRotate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sliderRotate.setForeground(new java.awt.Color(255, 255, 255));
        sliderRotate.setMajorTickSpacing(1);
        sliderRotate.setMaximum(3);
        sliderRotate.setMinorTickSpacing(1);
        sliderRotate.setPaintTicks(true);
        sliderRotate.setSnapToTicks(true);
        sliderRotate.setToolTipText("Rotate");
        sliderRotate.setValue(0);
        sliderRotate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderRotate.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panelToolLayout = new javax.swing.GroupLayout(panelTool);
        panelTool.setLayout(panelToolLayout);
        panelToolLayout.setHorizontalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTransform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProcessing, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(sliderCorrection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTypeImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBoxAntialiased, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBoxPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonDiagonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonCircular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCorrectionImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelToolLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sliderRotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelToolLayout.setVerticalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransform, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(checkBoxPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxAntialiased)
                .addGap(48, 48, 48)
                .addComponent(labelProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTypeImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonDiagonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCircular)
                .addGap(18, 18, 18)
                .addComponent(labelCorrectionImage)
                .addGap(18, 18, 18)
                .addComponent(sliderCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelToolLayout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(sliderRotate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setToolTipText("");

        menuFile.setText("File");

        menuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Open_24x24.png"))); // NOI18N
        menuItemOpen.setText("Open...");
        menuFile.add(menuItemOpen);

        menuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Close_24x24.png"))); // NOI18N
        menuItemClose.setText("Close");
        menuFile.add(menuItemClose);

        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Save_24x24.png"))); // NOI18N
        menuItemSave.setText("Save");
        menuFile.add(menuItemSave);

        menuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Save_24x24.png"))); // NOI18N
        menuItemSaveAs.setText("Save as...");
        menuFile.add(menuItemSaveAs);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Exit_24x24.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        menuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuItemUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Undo_24x24.png"))); // NOI18N
        menuItemUndo.setText("Undo");
        menuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUndoActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemUndo);

        menuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Redo_24x24.png"))); // NOI18N
        menuItemRedo.setText("Redo");
        menuEdit.add(menuItemRedo);

        menuItemReset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemReset.setText("Reset");
        menuItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemResetActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemReset);

        jMenuBar1.add(menuEdit);

        menuHelp.setText("Help");

        menuItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/Help_24x24.png"))); // NOI18N
        menuItemHelp.setText("Help");
        menuHelp.add(menuItemHelp);

        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defisheye/About_24x24.png"))); // NOI18N
        menuItemAbout.setText("About...");
        menuHelp.add(menuItemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUndoActionPerformed

    private void menuItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemResetActionPerformed

    private void checkBoxAntialiasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAntialiasedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAntialiasedActionPerformed

    private void imageLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imageLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_imageLabelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonTypeGroup;
    private javax.swing.JCheckBox checkBoxAntialiased;
    private javax.swing.JCheckBox checkBoxPreview;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelCorrectionImage;
    private javax.swing.JLabel labelProcessing;
    private javax.swing.JLabel labelRotate;
    private javax.swing.JLabel labelTransform;
    private javax.swing.JLabel labelTypeImage;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemRedo;
    private javax.swing.JMenuItem menuItemReset;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private javax.swing.JMenuItem menuItemUndo;
    private javax.swing.JPanel panelImages;
    private javax.swing.JPanel panelTool;
    private javax.swing.JRadioButton radioButtonCircular;
    private javax.swing.JRadioButton radioButtonDiagonal;
    private javax.swing.JSlider sliderCorrection;
    private javax.swing.JSlider sliderRotate;
    // End of variables declaration//GEN-END:variables
}
